services:
  call_logger:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3030:3333"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3333 -b '0.0.0.0'"
    networks:
      - shared-network

volumes:
  bundle_cache:

networks:
  shared-network:
    external: true